name: Deploy

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build the app
        run: |
          npm install
          npm run build --prod
      - name: Pull Docker image
        run: |
          docker pull fangchiawen/testdocker0404:latest
      - name: Run Docker container
        run: |
          docker run -d --rm -p 4200:4200 fangchiawen/testdocker0404:latest
      - name: Deploy the app to GitHub Pages
        run: |
          npm run ng -- deploy --no-silent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
